FROM python:3.10.6

#RUN RUN apt update && apt -y upgrade

RUN pip install --upgrade pip

WORKDIR /app

ADD streamlit_app.py __init__.py image.png .env requirements.txt /app/

COPY pages /app/pages

RUN pip install -r requirements.txt

CMD ["streamlit", "run", "streamlit_app.py"]